### PR TITLE
fix(workspace): Wait for publish to finish

### LINKED ISSUE #182: Publish failure in a workspace
I tried the current HEAD(87ac6f3) in a workspace and got publish failure.

```
Release
  sv-parser-error 0.4.0
  sv-parser-macros 0.4.0
  sv-parser-syntaxtree 0.4.0
  sv-parser-parser 0.4.0
  sv-parser-pp 0.4.0
  sv-parser 0.4.0
? [y/N]
y
[INFO ] Update sv-parser-error to version 0.4.0
[INFO ] Fixing sv-parser's dependency on sv-parser-error to `^0.4.0` (from `^0.3.0`)
[INFO ] Fixing sv-parser-pp's dependency on sv-parser-error to `^0.4.0` (from `^0.3.0`)
[master 275b9d6] Prepare to v0.4.0 of sv-parser-error
 3 files changed, 3 insertions(+), 3 deletions(-)
[INFO ] Update sv-parser-macros to version 0.4.0
[INFO ] Fixing sv-parser-parser's dependency on sv-parser-macros to `^0.4.0` (from `^0.3.0`)
[INFO ] Fixing sv-parser-syntaxtree's dependency on sv-parser-macros to `^0.4.0` (from `^0.3.0`)
[master 8413d1a] Prepare to v0.4.0 of sv-parser-macros
 3 files changed, 3 insertions(+), 3 deletions(-)
[INFO ] Update sv-parser-syntaxtree to version 0.4.0
[INFO ] Fixing sv-parser's dependency on sv-parser-syntaxtree to `^0.4.0` (from `^0.3.0`)
[INFO ] Fixing sv-parser-parser's dependency on sv-parser-syntaxtree to `^0.4.0` (from `^0.3.0`)
[INFO ] Fixing sv-parser-pp's dependency on sv-parser-syntaxtree to `^0.4.0` (from `^0.3.0`)
[master 412af29] Prepare to v0.4.0 of sv-parser-syntaxtree
 4 files changed, 4 insertions(+), 4 deletions(-)
[INFO ] Update sv-parser-parser to version 0.4.0
[INFO ] Fixing sv-parser's dependency on sv-parser-parser to `^0.4.0` (from `^0.3.0`)
[INFO ] Fixing sv-parser-pp's dependency on sv-parser-parser to `^0.4.0` (from `^0.3.0`)
[master 568f1de] Prepare to v0.4.0 of sv-parser-parser
 3 files changed, 3 insertions(+), 3 deletions(-)
[INFO ] Update sv-parser-pp to version 0.4.0
[INFO ] Fixing sv-parser's dependency on sv-parser-pp to `^0.4.0` (from `^0.3.0`)
[master 631a1ab] Prepare to v0.4.0 of sv-parser-pp
 2 files changed, 2 insertions(+), 2 deletions(-)
[INFO ] Update sv-parser to version 0.4.0
[master 62c6f53] Prepare to v0.4.0 of sv-parser
 3 files changed, 5 insertions(+), 3 deletions(-)
[INFO ] Running cargo publish on sv-parser-error
    Updating crates.io index
   Packaging sv-parser-error v0.4.0 (/home/hatta/work/repos/sv-parser/sv-parser-error)
   Verifying sv-parser-error v0.4.0 (/home/hatta/work/repos/sv-parser/sv-parser-error)
  Downloaded synstructure v0.12.3
   Compiling proc-macro2 v1.0.6
   Compiling unicode-xid v0.2.0
   Compiling cc v1.0.47
   Compiling libc v0.2.65
   Compiling syn v1.0.8
   Compiling failure_derive v0.1.6
   Compiling cfg-if v0.1.10
   Compiling rustc-demangle v0.1.16
   Compiling quote v1.0.2
   Compiling backtrace-sys v0.1.32
   Compiling backtrace v0.3.40
   Compiling synstructure v0.12.3
   Compiling failure v0.1.6
   Compiling sv-parser-error v0.4.0 (/home/hatta/work/repos/sv-parser/target/package/sv-parser-error-0.4.0)
    Finished dev [unoptimized + debuginfo] target(s) in 10.55s
   Uploading sv-parser-error v0.4.0 (/home/hatta/work/repos/sv-parser/sv-parser-error)
[INFO ] Running cargo publish on sv-parser-macros
    Updating crates.io index
   Packaging sv-parser-macros v0.4.0 (/home/hatta/work/repos/sv-parser/sv-parser-macros)
   Verifying sv-parser-macros v0.4.0 (/home/hatta/work/repos/sv-parser/sv-parser-macros)
   Compiling proc-macro2 v1.0.6
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.8
   Compiling quote v1.0.2
   Compiling sv-parser-macros v0.4.0 (/home/hatta/work/repos/sv-parser/target/package/sv-parser-macros-0.4.0)
    Finished dev [unoptimized + debuginfo] target(s) in 14.96s
   Uploading sv-parser-macros v0.4.0 (/home/hatta/work/repos/sv-parser/sv-parser-macros)
[INFO ] Running cargo publish on sv-parser-syntaxtree
    Updating crates.io index
   Packaging sv-parser-syntaxtree v0.4.0 (/home/hatta/work/repos/sv-parser/sv-parser-syntaxtree)
   Verifying sv-parser-syntaxtree v0.4.0 (/home/hatta/work/repos/sv-parser/sv-parser-syntaxtree)
error: failed to verify package tarball

Caused by:
  failed to select a version for the requirement `sv-parser-macros = "^0.4.0"`
  candidate versions found which didn't match: 0.3.7, 0.3.6, 0.3.5, ...
  location searched: crates.io index
required by package `sv-parser-syntaxtree v0.4.0 (/home/hatta/work/repos/sv-parser/target/package/sv-parser-syntaxtree-0.4.0)`
```

`Uploading sv-parser-macros v0.4.0` seems to be completed, but the next update can't find `sv-parser-macros v0.4.0`.

I tried to insert a sleep between each publish like below:

```
diff --git a/src/main.rs b/src/main.rs
index a5166e6..b068e79 100755
--- a/src/main.rs
+++ b/src/main.rs
@@ -551,6 +551,7 @@ fn release_packages<'m>(
             if !cargo::publish(dry_run, &pkg.manifest_path, features)? {
                 return Ok(103);
             }
+            std::thread::sleep(std::time::Duration::from_secs(10));
         }
     }
```

The patched version works fine.
Maybe any confirmation or waiting of crates.io's index update is required.

### PR DESCRIPTION
**Pull request by epage**
A while back, publishing a crate was made asynchronous from
`cargo-publish`.  The problem is if we publish a crate at the bottom of
the dependency tree and then publish something that depends on it, that
can fail the test-compile because the crate is unavailable.  We didn't
run into problems before because usually we did enough stuff between
publish calls that it was done by the time we hit the next crate.
Switching to batch-processing broke this so now we are explicitly
waiting until the crate version is listed as published.

Fixes #182

### CODE REVIEW

File: src/cargo.rs [hunk 1]
```diff
@@ -54,6 +54,42 @@ pub fn publish(
...
+pub fn wait_for_publish(
+    name: &str,
+    version: &str,
+    timeout: std::time::Duration,
+    dry_run: bool,
+) -> Result<(), FatalError> {
+    if !dry_run {
+        let now = std::time::Instant::now();
+        let sleep_time = std::time::Duration::from_secs(1);
+        let client = crates_io_api::SyncClient::new();
```
Comment (sunng87) [inline src/cargo.rs]: We'd better add a line of log to tell user we are waiting for crates.io to sync.

Comment (epage) [reply src/cargo.rs]: Good idea.  Added.
